import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  CalendarOutline,
  UserOutline,
  OrderedListOutline,
  ArrowLeftOutline,
  LockOutline,
  ManOutline,
  StarOutline,
  IdcardOutline,
  PhoneOutline,
  MailOutline,
  EnvironmentFill,
  EnvironmentOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline, 
  MenuUnfoldOutline, 
  DashboardOutline, 
  FormOutline, 
  CalendarOutline,
  UserOutline,
  OrderedListOutline,
  ArrowLeftOutline,
  LockOutline,
  ManOutline,
  StarOutline,
  IdcardOutline,
  PhoneOutline,
  MailOutline,
  EnvironmentOutline,
];